- name: open_mariadb_port
  firewalld: 
    port: 3306/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: restart_mariadb
  service: 
    name: mariadb
    state: restarted
  when: ansible_os_family == "RedHat"

- name: restart_mariadb
  service: 
    name: mysql
    state: restarted
  when: ansible_os_family == "Debian"
