---
- name: Update yum
  yum: 
    name: "*"
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Update apt
  apt:
    update_cache: yes
    upgrade: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: Install core 'devel' packages in CentoS/Redhat
  yum: 
    name: "@Development tools"
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install core 'devel' packages in Debian/Ubuntu
  apt: 
    name: "build-essential"
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: install firewalld
  yum: 
    name: "firewalld"
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"
   
- name: install firewalld
  apt:
    name: "firewalld"
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: install systemd in Debian servers
  apt:
    name: "systemd"
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: install python-selinux in Debian servers
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - policycoreutils
    - python-selinux
    - selinux-basics
  when: ansible_os_family == "Debian"

- name: install policycoreutils-python in RedHat servers
  yum:
    name: "policycoreutils-python"
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: set selinux to Enforcing
  selinux:
    policy: targeted
    state: enforcing
  when: ansible_os_family == "RedHat"
