---
- name: Update yum
  yum: 
    name: "*"
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Update apt
  apt:
    update_cache: yes
    upgrade: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: Install core 'devel' packages in CentoS/Redhat
  yum: 
    name: "@Development tools"
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install core 'devel' packages in Debian/Ubuntu
  apt: 
    name: "build-essential"
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: install firewalld
  yum: 
    name: "firewalld"
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"
   
- name: install firewalld
  apt:
    name: "firewalld"
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"
