---
- name: Install MariaDB and it's dependencies
  yum: 
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - MySQL-python
    - php-mysql
  when: ansible_os_family == "RedHat"

- name: Install MariaDB and it's dependencies
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - mysql-server
    - python-mysqldb
    - libmysqld-dev
  when: ansible_os_family == "Debian"

- name: Enable MariaDB
  systemd: 
    name: mariadb
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Enable MariaDB
  systemd: 
    name: mysql
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

  notify:
    - open_mariadb_port
    - restart_mariadb
