---

- name: create apache vhost dirs - RedHat
  file:
    path: "/etc/httpd/{{ item }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"
  with_items:
    - "sites-available"
    - "sites-enabled"
  when: ansible_os_family == "RedHat"

- name: create apache vhost dirs - Debian
  file:
    path: "/etc/apache2/{{ item }}"
    state: directory
    mode: 0755
    owner: "root"
    group: "root"
  with_items:
    - "sites-available"
    - "sites-enabled"
  when: ansible_os_family == "Debian"

- name: Include new Apache dirs using IncludeOptional in main apache conf - RedHat
  lineinfile:
    dest: "/etc/httpd/conf/httpd.conf"
    regexp: "^IncludeOptional sites-enabled"
    line: "IncludeOptional sites-enabled/*.conf"
    state: present
  when: ansible_os_family == "RedHat"

- name: Include new Apache dirs using IncludeOptional in main apache conf - Debian
  lineinfile:
    dest: "/etc/apache2/apache2.conf"
    regexp: "^IncludeOptional sites-enabled"
    line: "IncludeOptional sites-enabled/*.conf"
    state: present
  when: ansible_os_family == "Debian"

- name: Copy Apache config file to Debian
  template: 
    src: "files/apache.j2"
    dest: "/etc/apache2/sites-available/{{ wpdomain }}.conf"
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"

- name: Copy Apache config file to RedHat
  template: 
    src: "files/apache.j2"
    dest: "/etc/httpd/sites-available/{{ wpdomain }}.conf"
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat"

- name: a2ensite for Debian
  command: "a2ensite {{ wpdomain }}.conf"
  when: ansible_os_family == "Debian"

- name: symlink for RedHat vhost
  file:
    src: "/etc/httpd/sites-available/{{ wpdomain }}.conf"
    dest: "/etc/httpd/sites-enabled/{{ wpdomain }}.conf"
    owner: root
    group: root
    state: link
  when: ansible_os_family == "RedHat"

  notify:
    - restart_httpd
    - restart_apache2
