---
- name: Create a new WP user
  user:
    name: "{{ wpuser_name }}"
    password: "{{ wpuser_pass }}"
    shell: "/bin/bash"

- name: Create directories
  file:
    path: "/home/{{ wpuser_name }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ wpuser_name }}"
    group: "{{ wpuser_name }}"
  with_items:
    - "public_html"
    - "logs"

- name: Change home dir permissions
  file:
    path: "/home/{{ wpuser_name }}/"
    mode: 0711

- name: Change context of logs dir
  sefcontext:
    target: "/home/{{ wpuser_name }}/logs"
    setype: httpd_log_t
    state: present
  when: ansible_os_family == "RedHat"

- name: Change context of public_html dir
  sefcontext:
    target: "/home/{{ wpuser_name }}/public_html"
    setype: httpd_sys_content_t
    state: present
  when: ansible_os_family == "RedHat"
 
- name: Copy our index.html to the remote Redhat server
  copy: 
    src: "files/index_redhat.html"
    dest: "/home/{{ wpuser_name }}/public_html/index.html"
    owner: "{{ wpuser_name }}"
    group: "{{ wpuser_name }}"
    mode: 0644
    backup: yes
  when: ansible_os_family == "RedHat"

- name: Copy our index.html to the remote Debian server
  copy: 
    src: "files/index_debian.html"
    dest: "/home/{{ wpuser_name }}/public_html/index.html"
    owner: "{{ wpuser_name }}"
    group: "{{ wpuser_name }}"
    mode: 0644
    backup: yes
  when: ansible_os_family == "Debian"
