---

- name: Create a new secondary, non-root, sudo user
  user: 
    name: "{{ sudouser_name }}"
    password: "{{ sudouser_pass }}"
    shell: "/bin/bash"

- name: Add remote authorized key for passwordless auth
  authorized_key: 
    user: "{{ sudouser_name }}"
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: Check if 'sudo' exists on CentOS/RedHat
  yum: 
    name: sudo
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Check if 'sudo' exists on Debian/Ubuntu
  apt: 
    name: sudo
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: Check and confirm if the remote server have a 'wheel' group
  group: 
    name: wheel
    state: present

- name: Allow passwordless sudo for the 'wheel' group
  lineinfile: 
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'

- name: Add the new user to the 'wheel' group
  user: 
    name: "{{ sudouser_name }}"
    groups: wheel
    append: yes
