---
- name: Install PHP and other required modules
  yum: 
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-mbstring
    - php-pdo
    - php-pear
    - php-mysql
    - php-gd
    - php-fpm
    - php-xml
  when: ansible_os_family == "RedHat"

- name: Install PHP and other required modules
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - php5
    - php5-mysql
    - php-pear
    - php5-cli
    - php5-common
    - php5-dev
    - libapache2-mod-php5
    - php5-fpm
    - php5-gd
  when: ansible_os_family == "Debian"

  notify:
    - restart_httpd
    - restart_apache2
