---
    # Install PHP and all the necessary PHP modules
    - name: Install PHP and other required modules
      yum: name={{ item }}
           update_cache=yes
           state=latest
      with_items:
        - php
        - php-cli
        - php-common
        - php-devel
        - php-mbstring
        - php-pdo
        - php-pear
        - php-mysql
        - php-gd
        - php-fpm
        - php-xml
